### ISSUE TITLE
post install task needs to use svc instead of se abbreviation

### ISSUE THREAD

**Issue by JayKayy** [rhtconsulting/rhc-ose#39]
After install completes it looks as though one of the Post install tasks uses the abbreviation `se` instead of `svc` to get a service

```
Post Install
Adding password for user joe
Adding password for user alice
Error from server: error when creating "STDIN": serviceaccounts "router" already exists
password for stats user admin has been set to 9Il9E9QIFr
deploymentconfigs/router-default
services/router-default
error: no resource "se" has been defined
```

**Comment by etsauer** [comment]
@JayKayy thanks for this. Probably the best solution is to completely spell out the resource types rather than using the abbreviations. Would you be willing to submit the change? I can show you where we're using abbreviations for resource types:

https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/provisioning/osc-install#L228

https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/provisioning/osc-install#L267

https://github.com/rhtconsulting/rhc-ose/blob/openshift-enterprise-3/provisioning/osc-install#L267

**Comment by etsauer** [comment]
This was taken care of with https://github.com/rhtconsulting/rhc-ose/pull/41 so I'm going to close this issue.
